# K8s ServiceAccount annotated with GCP SA email
# This is the GCP equivalent of the IRSA annotation in AWS
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
  annotations:
    # Paste the value from terraform output "workload_identity_annotation"
    iam.gke.io/gcp-service-account: *****@app-project.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test-pod
  namespace: app
spec:
  serviceAccountName: app-sa
  containers:
    - name: gcloud
      image: google/cloud-sdk:slim
      command: ["sleep", "3600"]
